### PR TITLE
Optimized calls to EditorBuildSettings.scenes

### PR DESCRIPTION
**Pull request by hbollon**
Hey ! 👋
I optimized calls to EditorBuildSettings.scenes in GetBuildScene function for performance gain and to avoid freeze when we have a lot of scenes to handle.
I also did some grammar fixes :)

### CODE REVIEW

**Comment by starikcetin** [comment]
Thanks, I'll check this out when I get the chance.

**Comment by starikcetin** [comment]
Also, @JohannesMP can you give it a review as well?

**Review by starikcetin — APPROVED** [review]

**Comment by starikcetin** [comment]
Thank you. I don't have access to my PC right now, I will publish a new release when I get my hands on it.

**Comment by hbollon** [comment]
You're welcome and thanks to you and @JohannesMP for this very useful project! :smile:

**Comment by starikcetin** [comment]
Included in version 1.1.1

**Pull request merged**
